### ISSUE TITLE
inspirobot flow.images broke

### ISSUE THREAD

**Issue by Valwoe** [SamHDev/inspiro#3]
The flow object no longer carry an [].image.url . 

The following code does not work anymore :  
`flow = inspirobot.flow() 
for quote in flow:
    print(quote.image.url)`

**Comment by SamHDev** [comment]
Hello!

Thanks for raising this issue.

I'm not getting any errors with your code-snippet?

Example: 
![image](https://user-images.githubusercontent.com/21042247/189551678-2d2dd72a-8a2f-483f-972b-b3d8d6bd66a3.png)

Could you give me more information of your current python install so I can try to replicate this issue.

Warm Regards,
Sam.

**Comment by Valwoe** [comment]
Hello,
thanks for your quick response. Here are more details : 

My whole code is this : 

![image](https://user-images.githubusercontent.com/45520322/189625174-99b04f62-5e06-46fb-b32a-cbe8ed8b4074.png)

My python version is 3.10.4.

I am using a linux Computer (Ubuntu). I replicated the same issue in an other computer (same  OS but with new install).

Inspiro was installed using PIP.

When I launch this program, it goes into the for loop, but doesn't pint anything, just hang here waiting forever. After an controle-C (a keyboard interrupt) , here is the result : 

```valentin@valentin-Latitude3570:~/Documents/Program/Pythons projects/Bots/Inspirobot$ /bin/python3 "/home/valentin/Documents/Program/Pythons projects/tempo_test_only.py"
https://source.unsplash.com/z0MzknEtVZM/1600x900
Traceback (most recent call last):
  File "/home/valentin/Documents/Program/Pythons projects/tempo_test_only.py", line 5, in <module>
    print(quote.image.url)
  File "/home/valentin/.local/lib/python3.10/site-packages/inspirobot/flow.py", line 134, in url
    return self.image_url()
  File "/home/valentin/.local/lib/python3.10/site-packages/inspirobot/flow.py", line 137, in image_url
    r = requests.get("https://source.unsplash.com/{}/{}x{}".format(self.id, width, height))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt```

photo of this error text if github messes up the new lines : 

![image](https://user-images.githubusercontent.com/45520322/189626564-3df39d06-4f0d-42c7-8d2a-76abb3d5b92e.png)

**Comment by SamHDev** [comment]
Thanks for your speedy reply.

This is quite strange.
It seems to be printing the first URL, but the request to unsplash seems to fail on the second.

Perhaps being rate limited?

I'll push an update that will change the behaviour of `InspiroBotFlowImage.image_url` so It no-longer performs this request.

I'm not sure why it does this in the first place.

I'll update you when this is done.

Warm Regards,
Sam.

**Comment by SamHDev** [comment]
Update pushed as `0.0.3`

Let me know if it works so I can close the issue!

Warm Regards,
Sam.

**Comment by Valwoe** [comment]
thanks for your reactivity. Unfortunately, it didn't fix my problem. 

here is the output showing that I applied the 0.0.3 update; 


```
pip show inspiro
Name: inspiro
Version: 0.0.3
Summary: Python3 API wrapper for InspiroBot
Home-page: https://github.com/SamHDev/inspiro
Author: SamHDev
Author-email: sam.fucked.up@samh.dev
License: UNKNOWN
Location: /home/valentin/.local/lib/python3.10/site-packages
Requires: 
Required-by: 
```

and here is the output form the same code sniplet. 


```valentin@valentin-Latitude3570:~/Documents/Program/Pythons projects$ python3 tempo_test_only.py 
^CTraceback (most recent call last):
  File "/home/valentin/Documents/Program/Pythons projects/tempo_test_only.py", line 5, in <module>
    print(quote.image.url)
  File "/home/valentin/.local/lib/python3.10/site-packages/inspirobot/flow.py", line 134, in url
    return self.image_url()
  File "/home/valentin/.local/lib/python3.10/site-packages/inspirobot/flow.py", line 137, in image_url
    r = requests.get("https://source.unsplash.com/{}/{}x{}".format(self.id, width, height))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt```

It's very strange that I'm the only one having such a problem, even more since it didn't for more than 6 month before it appeared. Maybe it is a change in my local configuration or my local internet service ? 

I hope you will be able to fix this without too much problem --'

Warm regard, 
Valentin

**Comment by Valwoe** [comment]
maybe the problem lies in the requests package ? 
I currently have the version 2.25.1 installed.
